[package]
name = "pigeon"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
clap = { version = "4.4.18", features = ["derive"] }
dirs = "5.0.1"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
thiserror = "1.0.56"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
ureq = { version = "2.9.7", features = ["json"] }
