version = "0.1.0"
#---------------- env ----------------#
[[environment]]
name = "staging"
[[environment.service]]
name = "httpbin"
scheme = "https"
host = "httpbin.org"

[[environment]]
name = "dev"
[[environment.service]]
name = "httpbin"
scheme = "http"
host = "httpbin.org"

#---------------- services ----------------#
[[service]]
name = "httpbin"
alias = "hb"
[[service.endpoint]]
name = "method-get"
alias = "get"
method = "get"
path = "/get"
headers = [["abc", "def"]]
[[service.endpoint.pre_hook]]
script  = "./example-prehook.nu"
