version = "0.1.0"
#---------------- env ----------------#
[[environment]]
name = "staging"
[[environment.service]]
name = "httpbin"
scheme = "https"
host = "httpbin.org"

[[environment]]
name = "dev"
[[environment.service]]
name = "httpbin"
scheme = "http"
host = "httpbin.org"

#---------------- services ----------------#
[[service]]
name = "httpbin"
alias = "hb"
[[service.endpoint]]
name = "method-get"
alias = "get"
method = "get"
path = "/get"
headers = [["x-abc", "d, ef"], ["x-abc", "huh"]]
[[service.endpoint.pre_hook]]
script  = "./example-prehook.nu"

[[service.endpoint]]
name = "method-post"
alias = "post"
method = "post"
path = "/post"
headers = [["key", "value"]]
[service.endpoint.body]
kind = "application/json"
data = '{"a": "b", "c": [1,2,3]}'


[[service.endpoint]]
name = "dyn data bytes get"
alias = "bytes"
method = "get"
path = "/bytes/100"
[[service.endpoint.post_hook]]
script = "./example-posthook.nu"
