[environment.dev]
scheme = "http"
host = "httpbin.org"
headers = {a= "b", c="d"}

[environment.dev.store]
key_1 = "value_1"
key_2 = "value_4"

# -------------------------------------------------------

[environment.prod]
scheme = "https"
host = "httpbin.org"

[environment.prod.store]
key_1 = "value_2"

# =======================================================

[endpoint.get]
alias = "g"
description= "yes this gets some random data from httpbin"
path = "/get"
method = "get"
headers = {x-abc= "d, e", header-key = "header-value"}
pre_hook.script = "./example-prehook.nu"

[endpoint.post]
path = "/post"
method = "post"
body = {kind = "application/json", data = '{"a": "b", "c": [1,2,3]}'}

