type = "http"

[environment.dev]
scheme = "http"
host = "localhost"
port = 80

[environment.staging]
scheme = "https"
host = "httpbin.org"

[query.get]
description = "get something"
path = "/get"
method = "GET"
args = [["abc", "def"], ["h", "i"]]
headers = {"custom" = "hab"}

[query.delete]
description = "delete something"
path = "/delete"
method = "DELETE"

[query.post]
description = "post data"
path = "/post"
method = "POST"
body."application/json".inline = '''{"a": "b"}'''
pre_hook.script = "./example-hooks/httpbin/post.nu"

[query.patch]
description = "patch xml data"
path = "/patch"
method = "PATCH"
body.raw_text ={ content_type = "application/xml",  data.inline = '''<a>content</a>'''}

[query.put]
description = "put raw binary blob"
path = "/put"
method = "PUT"
body.raw ={ content_type = "raw/data",  data.file = '''./example-body/blob'''}


[group.methods]
type = "http"

[group.methods.environment.staging]
scheme = "https"
host = "httpbin.org"
