name: basic sanity checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check format
      run: cargo fmt --check --verbose
    - name: Build
      run: cargo clippy --verbose
    - name: Run tests
      run: cargo test --verbose

